import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import tailwindcss from '@tailwindcss/vite'

// Custom plugin to inline CSS for PageSpeed Optimization
const inlineCssPlugin = () => {
  return {
    name: 'inline-css',
    transformIndexHtml: {
      order: 'post',
      handler(html, ctx) {
        if (!ctx.bundle) return html

        let cssCode = ''
        // Find CSS file and extract its content
        for (const [fileName, file] of Object.entries(ctx.bundle)) {
          if (fileName.endsWith('.css')) {
            cssCode = file.source
            // Prevent the CSS file from being emitted
            delete ctx.bundle[fileName]
            break
          }
        }

        if (cssCode) {
          // Remove injected <link rel="stylesheet"> generated by Vite
          let newHtml = html.replace(/<link[^>]*rel="stylesheet"[^>]*>/g, '')
          // Remove preload links for CSS if any
          newHtml = newHtml.replace(
            /<link[^>]*rel="(?:module)?preload"[^>]*href="[^"]+\.css"[^>]*>/g,
            ''
          )
          // Inject <style> before </head>
          return newHtml.replace('</head>', `<style>${cssCode}</style>\n</head>`)
        }

        return html
      },
    },
  }
}

// https://vite.dev/config/
export default defineConfig({
  plugins: [vue(), tailwindcss(), inlineCssPlugin()],
  test: {
    environment: 'jsdom',
  },
})
