// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 12/03/2026, 08:52:25
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
import cfg3 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["D:/xampp/htdocs/docanto.net/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/xampp/htdocs/docanto.net/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/xampp/htdocs/docanto.net/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/xampp/htdocs/docanto.net/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/xampp/htdocs/docanto.net/plugins/**/*.{js,ts,mjs}","D:/xampp/htdocs/docanto.net/composables/**/*.{js,ts,mjs}","D:/xampp/htdocs/docanto.net/utils/**/*.{js,ts,mjs}","D:/xampp/htdocs/docanto.net/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/xampp/htdocs/docanto.net/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","D:/xampp/htdocs/docanto.net/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","D:/xampp/htdocs/docanto.net/app.config.{js,ts,mjs}"]}},
{},
cfg2,
cfg3
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;